//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_tnBlog
    {
        public string BlogID { get; set; }
        public string BlogTitle { get; set; }
        public string BlogBannerURl { get; set; }
        public string BlogDetail { get; set; }
        public string CreateByID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string MemberName { get; set; }
    }
}
